# Generated by Django 3.2.12 on 2023-03-29 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0053_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 12, 44, 53, 515204, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
